# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 1.3
  - nightly

notifications:
  email: false

script:
  - julia --project --check-bounds=yes -e '
    import Pkg;
    Pkg.add(Pkg.PackageSpec(url="https://github.com/pseastham/eFEM.jl"));
    Pkg.add(Pkg.PackageSpec(url="https://github.com/pseastham/StokesParticlesBuilder"));
    Pkg.add(Pkg.PackageSpec(url="https://github.com/pseastham/StokesParticles.jl"));
    Pkg.build();
    Pkg.test("eFEM"; coverage=false)
    Pkg.test("StokesParticles"; coverage=false)
    Pkg.test("eFEMpart"; coverage=true)'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.3
      script: julia --project=docs -e '
          using Pkg;
          Pkg.add(PackageSpec(url="https://github.com/pseastham/eFEM.jl"));
          Pkg.add(PackageSpec(url="https://github.com/pseastham/StokesParticlesBuilder"));
          Pkg.add(PackageSpec(url="https://github.com/pseastham/StokesParticles.jl"));
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
